version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./greenguard-app/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./greenguard-app/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'greenguard'
      MYSQL_PASS: 'password'
    volumes:
      - ./db-data:/var/lib/mysql
    networks:
      - internal
  api:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
  greenguard-api:
    build:
      context: ./greenguard-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
networks:
  internal:
    driver: bridge